# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
repos:
# Default hooks generally useful
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=500']
# Hooks for code formatting, linting, type checking, security
-   repo: local
    hooks:
    -   id: black-formatting-hook
        name: Run autoformatting black
        entry: bash -xc 'black --config pyagentspec/pyproject.toml -- "$@"' --
        language: system
        types_or: [python]
        # 'verbose:' when set to true, makes the pre-commit framework itself verbose. This means more detailed logging
        # about what the pre-commit framework is doing, not just the hook. Useful for debugging or understanding the hook's behavior.
        verbose: true
    -   id: isort-formatting-hook
        name: Run autoformatting isort
        entry: bash -xc 'isort --settings-path pyagentspec/pyproject.toml -- "$@"' --
        language: system
        types_or: [python]
        # 'verbose:' when set to true, makes the pre-commit framework itself verbose. This means more detailed logging
        # about what the pre-commit framework is doing, not just the hook. Useful for debugging or understanding the hook's behavior.
        verbose: true
    -   id: flake8-linter-hook
        name: Run Flake8 linter
        entry: bash -xc 'flake8 --select C801 -- "$@"' --
        language: system
        types_or: [python]
        # 'verbose:' when set to true, makes the pre-commit framework itself verbose. This means more detailed logging
        # about what the pre-commit framework is doing, not just the hook. Useful for debugging or understanding the hook's behavior.
        verbose: true
    -   id: flake8-linter-hook-copyright
        name: Run Flake8 linter to check for the copyright
        entry: bash -xc 'flake8 --select C801 --copyright-check --copyright-regexp="# Copyright \(C\) [0-9]{4}(, [0-9]{4})* Oracle and/or its affiliates.\n#\n# This software is under the Apache License 2.0\n# \(LICENSE-APACHE or http://www.apache.org/licenses/LICENSE-2.0\) or Universal Permissive License\n# \(UPL\) 1.0 \(LICENSE-UPL or https://oss.oracle.com/licenses/upl\), at your option." -- "$@"' --
        language: system
        types_or: [python]
        # 'verbose:' when set to true, makes the pre-commit framework itself verbose. This means more detailed logging
        # about what the pre-commit framework is doing, not just the hook. Useful for debugging or understanding the hook's behavior.
        verbose: true
    -   id: bandit-security-hook
        name: Run bandit security checks
        entry: bandit -c bandit.yaml --
        language: system
        types_or: [python]
    -   id: mypy-type-checking-hook
        name: Run type checking (mypy)
        entry: bash -xc 'mypy -- "$@"' --
        language: system
        types_or: [python]
        # We exclude the fuzz tests from this check
        exclude: '(.?tests_fuzz/.)'
        # 'verbose:' when set to true, makes the pre-commit framework itself verbose. This means more detailed logging
        # about what the pre-commit framework is doing, not just the hook. Useful for debugging or understanding the hook's behavior.
        verbose: true
